/**
* Generated by TxSchemeTypeScriptPlugin. DO NOT EDIT.
*/

import { TRANSACTIONS } from '../src/';
import { config } from "@wavesenterprise/signature-generator";
import * as expect from 'expect';

const decoder = new TextDecoder('utf-8');

describe('', () => {
  beforeEach(() => {
    config.set({networkByte: 84, crypto: 'waves'})
  });
  
  it('RegisterNode', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      targetPubKey: "FM5ojNqW7e9cZ9zhPYGkpSP1Pcd8Z3e3MNKYVS5pGJ8Z",
      nodeName: "node-0",
      opType: "add",
      timestamp: 1598008066632,
      fee: 1000000
    };
    const signatureGenerator = TRANSACTIONS.RegisterNode.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('RegisterNodeV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      targetPubKey: "FM5ojNqW7e9cZ9zhPYGkpSP1Pcd8Z3e3MNKYVS5pGJ8Z",
      nodeName: "node-0",
      opType: "add",
      timestamp: 1598008066632,
      fee: 1000000,
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.RegisterNode.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateAliasV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      alias: "John",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.CreateAlias.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateAliasV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      alias: "John",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.CreateAlias.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateAliasV4', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      alias: "John",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.CreateAlias.V4(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('IssueV2', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      name: "D56Gk8tvSAhNesghXgjAw67rSYDf4F2vo7HmsFTuGweC",
      description: "Some script",
      quantity: 10000000,
      decimals: 2,
      reissuable: true,
      fee: 1000000,
      timestamp: 1598008066632,
      script: "base64:3rbFDtbPwAvSp2vBvqGfGR9nRS1nBVnfuSCN3HxSZ7fVRpt3tuFG5JSmyTmvHPxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtE"
    };
    const signatureGenerator = TRANSACTIONS.Issue.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('IssueV3', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      name: "D56Gk8tvSAhNesghXgjAw67rSYDf4F2vo7HmsFTuGweC",
      description: "Some script",
      quantity: 10000000,
      decimals: 2,
      reissuable: true,
      fee: 1000000,
      timestamp: 1598008066632,
      atomicBadge: "",
      script: "base64:3rbFDtbPwAvSp2vBvqGfGR9nRS1nBVnfuSCN3HxSZ7fVRpt3tuFG5JSmyTmvHPxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtE"
    };
    const signatureGenerator = TRANSACTIONS.Issue.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('ReissueV2', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      quantity: 10000000,
      reissuable: true,
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.Reissue.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('ReissueV3', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      quantity: 10000000,
      reissuable: true,
      fee: 1000000,
      timestamp: 1598008066632,
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.Reissue.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('BurnV2', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      amount: "100000000",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.Burn.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('BurnV3', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      amount: "100000000",
      fee: 1000000,
      timestamp: 1598008066632,
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.Burn.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('LeaseV2', async () => {
    const transaction = {
      assetId: "WAVES",
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      recipient: "3NiVPB1t32jC3SJpLomY3Zv6kwvfaJpRkqS",
      amount: "100000000",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.Lease.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('LeaseV3', async () => {
    const transaction = {
      assetId: "WAVES",
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      recipient: "3NiVPB1t32jC3SJpLomY3Zv6kwvfaJpRkqS",
      amount: "100000000",
      fee: 1000000,
      timestamp: 1598008066632,
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.Lease.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('LeaseCancelV2', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      fee: 1000000,
      timestamp: 1598008066632,
      leaseId: "E9yZC4cVhCDfbjFJCc9CqkAtkoFy5KaCe64iaxHM2adG"
    };
    const signatureGenerator = TRANSACTIONS.LeaseCancel.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('LeaseCancelV3', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      fee: 1000000,
      timestamp: 1598008066632,
      leaseId: "E9yZC4cVhCDfbjFJCc9CqkAtkoFy5KaCe64iaxHM2adG",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.LeaseCancel.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('SponsorFee', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      isEnabled: true,
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.SponsorFee.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('SponsorFeeV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      isEnabled: true,
      fee: 1000000,
      timestamp: 1598008066632,
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.SponsorFee.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('SetAssetScript', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      script: "base64:3rbFDtbPwAvSp2vBvqGfGR9nRS1nBVnfuSCN3HxSZ7fVRpt3tuFG5JSmyTmvHPxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtE",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.SetAssetScript.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('Data', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      authorPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      data: [{"type":"integer", "key": "height", "value": 100}],
      timestamp: 1598008066632,
      fee: 1000000
    };
    const signatureGenerator = TRANSACTIONS.Data.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('DataV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      authorPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      data: [{"type":"integer", "key": "height", "value": 100}],
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.Data.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('DataV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      authorPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      data: [{"type":"integer", "key": "height", "value": 100}],
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.Data.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('TransferV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      feeAssetId: "WAVES",
      timestamp: 1598008066632,
      amount: "100000000",
      fee: 1000000,
      recipient: "3NiVPB1t32jC3SJpLomY3Zv6kwvfaJpRkqS",
      attachment: "base64:3rbFDtbPwAvSp2vBvqGfGR9PxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtEiZ"
    };
    const signatureGenerator = TRANSACTIONS.Transfer.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('TransferV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      feeAssetId: "WAVES",
      timestamp: 1598008066632,
      amount: "100000000",
      fee: 1000000,
      recipient: "3NiVPB1t32jC3SJpLomY3Zv6kwvfaJpRkqS",
      attachment: "base64:3rbFDtbPwAvSp2vBvqGfGR9PxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtEiZ",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.Transfer.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('MassTransfer', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      transfers: [
        {"recipient":"3NgSJRdMYu4ZbNpSbyRNZLJDX926W7e1EKQ","amount":"1000000000"},
        {"recipient":"3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn","amount":"1000000000"},
        {"recipient":"3NpkC1FSW9xNfmAMuhRSRArLgnfyGyEry7w","amount":"1000000000"},
        {"recipient":"3NkZd8Xd4KsuPiNVsuphRNCZE3SqJycqv8d","amount":"1000000000"}
      ],
      timestamp: 1598008066632,
      fee: 1000000,
      attachment: "base64:3rbFDtbPwAvSp2vBvqGfGR9PxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtEiZ"
    };
    const signatureGenerator = TRANSACTIONS.MassTransfer.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('MassTransferV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      transfers: [
        {"recipient":"3NgSJRdMYu4ZbNpSbyRNZLJDX926W7e1EKQ","amount":"1000000000"},
        {"recipient":"3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn","amount":"1000000000"},
        {"recipient":"3NpkC1FSW9xNfmAMuhRSRArLgnfyGyEry7w","amount":"1000000000"},
        {"recipient":"3NkZd8Xd4KsuPiNVsuphRNCZE3SqJycqv8d","amount":"1000000000"}
      ],
      timestamp: 1598008066632,
      fee: 1000000,
      attachment: "base64:3rbFDtbPwAvSp2vBvqGfGR9PxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtEiZ",
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.MassTransfer.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('MassTransferV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      assetId: "WAVES",
      transfers: [
        {"recipient":"3NgSJRdMYu4ZbNpSbyRNZLJDX926W7e1EKQ","amount":"1000000000"},
        {"recipient":"3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn","amount":"1000000000"},
        {"recipient":"3NpkC1FSW9xNfmAMuhRSRArLgnfyGyEry7w","amount":"1000000000"},
        {"recipient":"3NkZd8Xd4KsuPiNVsuphRNCZE3SqJycqv8d","amount":"1000000000"}
      ],
      timestamp: 1598008066632,
      fee: 1000000,
      attachment: "base64:3rbFDtbPwAvSp2vBvqGfGR9PxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtEiZ",
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.MassTransfer.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('Permit', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      target: "3NiVPB1t32jC3SJpLomY3Zv6kwvfaJpRkqS",
      timestamp: 1598008066632,
      fee: 1000000,
      opType: "add",
      role: "miner",
      duplicate_timestamp: 1598008066632,
      dueTimestamp: 1572600785208
    };
    const signatureGenerator = TRANSACTIONS.Permit.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('PermitV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      target: "3NiVPB1t32jC3SJpLomY3Zv6kwvfaJpRkqS",
      timestamp: 1598008066632,
      fee: 1000000,
      opType: "add",
      role: "miner",
      duplicate_timestamp: 1598008066632,
      dueTimestamp: 1572600785208,
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.Permit.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreatePolicy', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyName: "SomeName",
      description: "Some script",
      recipients: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      owners: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      timestamp: 1598008066632,
      fee: 1000000
    };
    const signatureGenerator = TRANSACTIONS.CreatePolicy.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreatePolicyV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyName: "SomeName",
      description: "Some script",
      recipients: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      owners: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.CreatePolicy.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreatePolicyV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyName: "SomeName",
      description: "Some script",
      recipients: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      owners: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.CreatePolicy.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdatePolicy', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      recipients: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      owners: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      opType: "add",
      timestamp: 1598008066632,
      fee: 1000000
    };
    const signatureGenerator = TRANSACTIONS.UpdatePolicy.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdatePolicyV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      recipients: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      owners: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      opType: "add",
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.UpdatePolicy.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdatePolicyV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      recipients: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      owners: ["3NotQaBygbSvYZW4ftJ2ZwLXex4rTHY1Qzn", "3votNaBcgb25FdsdgsdSvYZW4ftJ2ZwLXex"],
      opType: "add",
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.UpdatePolicy.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('PolicyDataHashV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      dataHash: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      policyId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      timestamp: 1598008066632,
      fee: 1000000,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.PolicyDataHash.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContractV5', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      apiVersion: "1.1",
      payments: ""
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V5(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContract', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContractV6', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      apiVersion: "1.1",
      payments: "",
      isConfidential: "",
      groupParticipants: "",
      groupOwners: ""
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V6(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContractV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContractV7', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      payments: "",
      isConfidential: "",
      groupParticipants: "",
      groupOwners: "",
      bytecode: "",
      bytecodeHash: ""
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V7(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContractV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CreateContractV4', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      contractName: "SomeName",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      apiVersion: "1.1"
    };
    const signatureGenerator = TRANSACTIONS.CreateContract.V4(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContractV5', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      contractVersion: 2,
      feeAssetId: "WAVES",
      atomicBadge: "",
      payments: ""
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V5(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContract', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContractV6', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      contractVersion: 2,
      feeAssetId: "WAVES",
      atomicBadge: "",
      payments: ""
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V6(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContractV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      contractVersion: 2
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContractV7', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      contractVersion: 2,
      feeAssetId: "WAVES",
      atomicBadge: "",
      payments: "",
      callFunc: ""
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V7(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContractV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      contractVersion: 2,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('CallContractV4', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      params: [{"type":"integer", "key": "height", "value": 100}],
      fee: 1000000,
      timestamp: 1598008066632,
      contractVersion: 2,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.CallContract.V4(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('DisableContract', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.DisableContract.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('DisableContractV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.DisableContract.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('DisableContractV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.DisableContract.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdateContractV5', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      apiVersion: "1.1",
      groupParticipants: "",
      groupOwners: ""
    };
    const signatureGenerator = TRANSACTIONS.UpdateContract.V5(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdateContract', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.UpdateContract.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdateContractV6', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      groupParticipants: "",
      groupOwners: "",
      bytecode: "",
      bytecodeHash: ""
    };
    const signatureGenerator = TRANSACTIONS.UpdateContract.V6(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdateContractV2', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES"
    };
    const signatureGenerator = TRANSACTIONS.UpdateContract.V2(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdateContractV3', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: ""
    };
    const signatureGenerator = TRANSACTIONS.UpdateContract.V3(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('UpdateContractV4', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      contractId: "DP5MggKC8GJuLZshCVNSYwBtE6WTRtMM1YPPdcmwbuNg",
      image: "localhost:5000/smart-kv",
      imageHash: "b48d1de58c39d2160a4b8a5a9cae90818da1212742ec1f11fba1209bed0a212c",
      fee: 1000000,
      timestamp: 1598008066632,
      feeAssetId: "WAVES",
      atomicBadge: "",
      validationPolicy: 0,
      apiVersion: "1.1"
    };
    const signatureGenerator = TRANSACTIONS.UpdateContract.V4(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('SetScript', async () => {
    const transaction = {
      chainId: 1,
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      script: "base64:3rbFDtbPwAvSp2vBvqGfGR9nRS1nBVnfuSCN3HxSZ7fVRpt3tuFG5JSmyTmvHPxYf34SocMRkRKFgzTtXXnnv7upRHXJzZrLSQo8tUW6yMtE",
      name: "D56Gk8tvSAhNesghXgjAw67rSYDf4F2vo7HmsFTuGweC",
      description: "Some script",
      fee: 1000000,
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.SetScript.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })

  it('Atomic', async () => {
    const transaction = {
      senderPublicKey: "34qsNWsKKQaysTzpsf4aTyRS6Q1BoUuBntgGVj6SHZg3",
      transactions: "",
      timestamp: 1598008066632
    };
    const signatureGenerator = TRANSACTIONS.Atomic.V1(transaction);
    const bytes = await signatureGenerator.getBytes();
    
    expect(decoder.decode(bytes))
      .toEqual(
        decoder.decode(Int8Array.from(
          [0]
      )).toString()
    )
  })
});