package com.wavesenterprise.transaction.generator.base

import com.wavesenterprise.transaction.TxScheme

trait TypeScriptGenerator {
  protected val txTypesTsClassName    = "TRANSACTION_TYPES"
  protected val txVersionsTxClassName = "TRANSACTION_VERSIONS"

  protected def imports: Set[String] = Set.empty

  protected def buildWriter(schemes: Seq[TxScheme]): CodeWriter = CodeWriter()

  final def buildTypeScript(schemes: Seq[TxScheme]): String =
    CodeWriter()
      .addLines("""/**
                   |* Generated by TxSchemeTypeScriptPlugin. DO NOT EDIT.
                   |*/""".stripMargin)
      .newLine
      .combine(buildWriter(schemes))
      .build()
}
